### ISSUE TITLE
generator fails

### ISSUE THREAD

**Issue by JBusch** [Milanowicz/generator-typo3#1]
Sadly, the generator fails with the follwing output:

> /usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.all.js:8913
>                 throw e;
>                       ^
> SyntaxError: Unexpected token ;
>     at Function (<anonymous>)
>     at Function.template (/usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22)
>     at Typo3generator.underscore [as _engine](/usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/lib/util/engines.js:32:14)
>     at Typo3generator.engine (/usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
>     at Typo3generator.template (/usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
>     at Typo3generator.app (/usr/local/lib/node_modules/generator-typo3/app/index.js:364:10)
>     at /usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/lib/base.js:341:43
>     at /usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
>     at /usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
>     at iterate (/usr/local/lib/node_modules/generator-typo3/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)

**Comment by milanowicz** [comment]
Sorry, I was really busy, but I had fix it.
The if syntax in the ReadMe File was wrong.
